#!/usr/bin/env python

import argparse
import plistlib

import yaml


parser = argparse.ArgumentParser()
parser.add_argument('yaml')
parser.add_argument('plist')
args = parser.parse_args()


with open(args.yaml) as fh:
    yaml_content = fh.read()

content = yaml.load(yaml_content)

plist_content = plistlib.writePlistToString(content)

with open(args.plist, 'w') as fh:
    fh.write(plist_content)
